#!/bin/bash

if [ "$1" == "52" ];then
    user=Hongwei
    host="10.99.140.140"
    port=5222
elif [ "$1" == "140" ];then
    user=Hongwei
    host="10.15.201.88"
    port=14022
elif [ "$1" == "141" ];then
    user=Hongwei_Yao
    host="10.15.201.88"
    port=14122
elif [ "$1" == "142" ];then
    user=Hongwei
    host="10.15.201.88"
    port=14222
elif [ "$1" == "143" ];then
    user=Hongwei_Yao
    host="10.15.201.88"
    port=14322
elif [ "$1" == "144" ];then
    user=Hongwei
    host="10.15.201.88"
    port=14422
elif [ "$1" == "145" ];then
    user=Hongwei
    host="10.15.201.88"
    port=14522
elif [ "$1" == "91" ];then
    user=yhw
    host="10.99.140.140"
    port=9122
else
    user=Hongwei
    host="10.99.140.140"
    port=5222
fi

path="/home/homeway/project/Model-Reuse"
project="MetaV_Git"

/usr/bin/scp -r -P $port *.py $user@$host:$path/$project/
/usr/bin/scp -r -P $port bin $user@$host:$path/$project/
/usr/bin/scp -r -P $port config $user@$host:$path/$project/
/usr/bin/scp -r -P $port net $user@$host:$path/$project/
/usr/bin/scp -r -P $port datasets $user@$host:$path/$project/


sleep 1
echo "scp -P $port $user@$host:$path/$project/"